services:
  frnotend:
    build: task_app_front
    container_name: task-app-front
    ports:
      - 80:80
      - 443:443
  
  # backend:
  #   build: ea_backend
  #   container_name: ea-app-back
  #   depends_on:
  #     - postgres
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - BACKEND_PORT=8080
  #     - PGSQL_HOST=postgres
  #     - PGSQL_USER=${PGSQL_USER}
  #     - PGSQL_PORT=${PGSQL_PORT}
  #     - PGSQL_USER=${PGSQL_USER}
  #     - PGSQL_PASS=${PGSQL_PASS}
  #     - PGSQL_DB=${PGSQL_DB}
  
  postgres:
    image: postgres:17.2-alpine3.21
    container_name: ea-app-postgres
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/db_store:/var/lib/postgresql/data
      - ./postgresql/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASS}
      - POSTGRES_DB=${PGSQL_DB}
