server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;

    location = /authorize {
        try_files /authorize.html =404;
    }

    location / {
        try_files /index.html =404;
    }

    # 静的ファイル
    location ~* \.(js|css|png|svg|woff2?)$ {
        expires 6M;
        access_log off;
    }
}